name = "ArnoldiMethod"
uuid = "ec485272-7323-5ecc-a04f-4719b315124d"
author = ["Harmen Stoppels <me@harmenstoppels.nl>", "Lauri Nyman"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "0.8, 0.9, 0.10, 0.11, 0.12, 1.0"
julia = "1.3"

[extras]
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SparseArrays", "GenericSchur"]
